#将https://rubygems.org,换成https://gems.ruby-china.com/
#source "https://rubygems.org"
source "https://gems.ruby-china.com/"

gem "fastlane"
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
