# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
inhibit_all_warnings!

target 'iOS_Fastlane_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  # Pods for iOS_Fastlane_Demo

  target 'iOS_Fastlane_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_Fastlane_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end